name: tomopyui
channels:
  - astra-toolbox
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - ffmpeg
  - dask
  - dask-image
  - olefile
  - git
  - pip
  - tomopy
  - dxchange
  - jupyterlab
  - astropy
  - ipyfilechooser
  - ipywidgets
  - astra-toolbox
  - cudatoolkit
  - cupy
  - bqplot
  - pip:
      - bqplot-image-gl
      - tomoscan
