name: tomopyui-ipywidgets7
channels:
  - astra-toolbox
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - tomopy
  - dxchange
  - jupyterlab
  - astropy
  - ipyfilechooser
  - ipywidgets
  - widgetsnbextension
  - jupyterlab_widgets
  - ca-certificates
  - certifi
  - openssl
  - astra-toolbox
  - cudatoolkit
  - cupy
  - joblib
  - ipympl
  - bqplot
  - sphinx
  - jupyter_sphinx
  - numpydoc
  - sphinx-copybutton
  - sphinx-panels
  - sphinx-thebe
  - sphinx-togglebutton
  - sphinx-book-theme
  - sphinx-gallery
  - myst-nb
  - pip:
    - mpl-interactions
    - bqplot-image-gl