name: tomopyui_docs
channels:
  - astra-toolbox
  - conda-forge
  - defaults
dependencies:
  - python >=3.11,<3.12
  # build tools
  - python-build
  - pip
  - packaging
  - jupyter-packaging
  # Jupyter ecosystem
  - jupyterlab >=4,<5
  - jupyter_client
  # documentation tools
  - docutils # Removed version constraint to test compatibility
  - jupyterlab-myst
  - myst-nb >=0.17,<0.18
  - pandoc
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinxext-rediraffe
  - sphinx-panels
  - sphinx-thebe
  - sphinx-togglebutton
  - sphinx-book-theme
  - sphinx-gallery
  # demo and visualization
  - bqplot
  - ipykernel
  - ipyleaflet
  - matplotlib-base
  - numpy
  - scikit-image
  # tomopyui specific
  - matplotlib
  - ffmpeg
  - dask
  - dask-image
  - olefile
  - git
  - tomopy
  - dxchange
  - astropy
  - ipyfilechooser
  - ipywidgets
  - astra-toolbox
  - numpydoc
  - pip:
      - bqplot-image-gl
